skip_commits:
  files:
    - '**/*.md'
    - '**/*.html'
    - '**/*.yml'

image:
- Visual Studio 2015

environment:
  NugetApiKey:
    secure: Gxlox4/BGS+/9rX7ZRqAuA5bRzVFjYTKuyU8jpBbA5yfIzprQbzxZoAdhZxppRZ4
  GithubApiKey:
    secure: 2Lyii63Fi8aSnNDcC0cQaR11wrlpcpcs7/3+YBIdYupzpJRiD2F1gzJEJbgdrCLb

install:
  - ps: Install-Module PSGist -minimumVersion 2.0
  - ps: Install-Module BuildHelpers -minimumVersion 1.1.0
  - ps: Install-Module PSDepend -minimumVersion 0.2.5
  - ps: Install-Module PSake -minimumVersion 4.7
  - ps: Install-Module PSScriptAnalyzer 1.17.0
  - ps: Install-Module PSDeploy -minimumVersion 0.2.5
  - ps: Install-Module Pester -maximumVersion 3.4.0 -SkipPublisherCheck]

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

# version: 1.0.{build}
build: false

artifacts:
  path: $(BHProjectName)-$(APPVEYOR_BUILD_VERSION).zip

#deploy:
#  provider: GitHub
#  auth_token: $(GithubApiKey)
#  description: $(BHProjectName) release v$(APPVEYOR_BUILD_VERSION)
#  artifact: /$(BHProjectName)-$(APPVEYOR_BUILD_VERSION).zip/
#  draft: false
#  prerelease: false

# Kick off the CI/CD pipeline
test_script:
- ps: . .\build\build.ps1 -Task Deploy
